# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  check_apk:
    name: Check APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: whoopzee9/PayShare
      - name: Install python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.8
      - name: PIP install
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            requests
            pytest_check
            loguru
            pytest-html
            Appium-Python-Client
      - name: Test
        run: python3 -m pytest tests/api -v --html=report.html
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.html
